// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: file_audit.proto

package file_audit

import (
	context "context"
	common "github.com/sameersah/auditchain/proto_gen/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileAuditService_SubmitAudit_FullMethodName = "/fileaudit.FileAuditService/SubmitAudit"
)

// FileAuditServiceClient is the client API for FileAuditService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileAuditServiceClient interface {
	SubmitAudit(ctx context.Context, in *common.FileAudit, opts ...grpc.CallOption) (*FileAuditResponse, error)
}

type fileAuditServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileAuditServiceClient(cc grpc.ClientConnInterface) FileAuditServiceClient {
	return &fileAuditServiceClient{cc}
}

func (c *fileAuditServiceClient) SubmitAudit(ctx context.Context, in *common.FileAudit, opts ...grpc.CallOption) (*FileAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileAuditResponse)
	err := c.cc.Invoke(ctx, FileAuditService_SubmitAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileAuditServiceServer is the server API for FileAuditService service.
// All implementations must embed UnimplementedFileAuditServiceServer
// for forward compatibility.
type FileAuditServiceServer interface {
	SubmitAudit(context.Context, *common.FileAudit) (*FileAuditResponse, error)
	mustEmbedUnimplementedFileAuditServiceServer()
}

// UnimplementedFileAuditServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileAuditServiceServer struct{}

func (UnimplementedFileAuditServiceServer) SubmitAudit(context.Context, *common.FileAudit) (*FileAuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitAudit not implemented")
}
func (UnimplementedFileAuditServiceServer) mustEmbedUnimplementedFileAuditServiceServer() {}
func (UnimplementedFileAuditServiceServer) testEmbeddedByValue()                          {}

// UnsafeFileAuditServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileAuditServiceServer will
// result in compilation errors.
type UnsafeFileAuditServiceServer interface {
	mustEmbedUnimplementedFileAuditServiceServer()
}

func RegisterFileAuditServiceServer(s grpc.ServiceRegistrar, srv FileAuditServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileAuditServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileAuditService_ServiceDesc, srv)
}

func _FileAuditService_SubmitAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(common.FileAudit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileAuditServiceServer).SubmitAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileAuditService_SubmitAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileAuditServiceServer).SubmitAudit(ctx, req.(*common.FileAudit))
	}
	return interceptor(ctx, in, info, handler)
}

// FileAuditService_ServiceDesc is the grpc.ServiceDesc for FileAuditService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileAuditService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileaudit.FileAuditService",
	HandlerType: (*FileAuditServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitAudit",
			Handler:    _FileAuditService_SubmitAudit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_audit.proto",
}
